#!/bin/bash
#########################################################
###                                                   ###
###  Install and configure Zabbix Proxy               ###
###  https://github.com/apekatten/zabbix-scripts      ###
###                                                   ###
###  Supported versions:                              ###
###   - Ubuntu "Xenial" 16.04.x LTS                   ###
###                                                   ###
#########################################################

# Define defaults
default_server = "192.168.1.11"

# Is script running as root?
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

# Script running on correct OS? (Ubuntu "Xenial" 16.04 LTS)
if [[ $(lsb_release -sc) != "xenial" ]]; then
    echo "ERROR: Please use a supported version of Ubuntu!"
    echo "Gyldig versjon:     Ubuntu 16.04.x LTS"
    echo "Installert versjon:" $(lsb_release -sd)
    exit 1
fi

# Generate random password
randpw=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1)

# Ask user about config values
read -p "Hostname ["$(hostname)"]: " hostname
hostname=${hostname:-$(hostname)}
echo $hostname

read -p "Zabbix Server IP ["$default_server"]: " serverip
serverip=${serverip:-$default_server}
echo $serverip

read -p "MySQL Passord: [Generate random]" password
password=${password:-$randpw}
echo $password

# Update server and software
apt-get -y update
apt-get -y dist-upgrade

# Add Zabbix 3.2 repository
wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
dpkg -i zabbix-release_3.2-1+xenial_all.deb
apt-get -y update

# Install MySQL / MariaDB
debconf-set-selections <<< 'mysql-server mysql-server/root_password password '$password
debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password '$password
apt-get -y install mysql-server

# Create database
mysql -uroot -p$password -e "CREATE DATABASE zabbix_proxy"

# Install Zabbix Proxy and Agent
apt-get -y install zabbix-proxy-mysql zabbix-agent

# Add Zabbix schema to database
zcat /usr/share/doc/zabbix-proxy-mysql/schema.sql.gz | mysql -uroot -p$password zabbix_proxy

# Backup the default config files
mv /etc/zabbix/zabbix_proxy.conf /etc/zabbix/zabbix_proxy.conf.dist
mv /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf.dist

# Configure Zabbix Agent
echo "## Generated by script" $( date -u +"%F %H:%M UTC") > /etc/zabbix/zabbix_agentd.conf
echo "## Read more at https://github.com/apekatten/zabbix-scripts" >> /etc/zabbix/zabbix_agentd.conf
echo "PidFile=/var/run/zabbix/zabbix_agentd.pid" >> /etc/zabbix/zabbix_agentd.conf
echo "LogFile=/var/log/zabbix/zabbix_agentd.log" >> /etc/zabbix/zabbix_agentd.conf
echo "LogFileSize=0" >> /etc/zabbix/zabbix_agentd.conf
echo "Server=127.0.0.1" >> /etc/zabbix/zabbix_agentd.conf
echo "ServerActive=127.0.0.1" >> /etc/zabbix/zabbix_agentd.conf
echo "Hostname="$hostname >> /etc/zabbix/zabbix_agentd.conf
echo "Include=/etc/zabbix/zabbix_agentd.d/*.conf" >> /etc/zabbix/zabbix_agentd.conf

# Configure Zabbix Proxy
echo "## Generated by script" $( date -u +"%F %H:%M UTC") > /etc/zabbix/zabbix_proxy.conf
echo "## Read more at https://github.com/apekatten/zabbix-scripts" >> /etc/zabbix/zabbix_proxy.conf
echo "ProxyMode=0" >> /etc/zabbix/zabbix_proxy.conf
echo "Server="$serverip >> /etc/zabbix/zabbix_proxy.conf
echo "Hostname="$hostname >> /etc/zabbix/zabbix_proxy.conf
echo "LogFile=/var/log/zabbix/zabbix_proxy.log" >> /etc/zabbix/zabbix_proxy.conf
echo "LogFileSize=0" >> /etc/zabbix/zabbix_proxy.conf
echo "PidFile=/var/run/zabbix/zabbix_proxy.pid" >> /etc/zabbix/zabbix_proxy.conf
echo "DBName=zabbix_proxy" >> /etc/zabbix/zabbix_proxy.conf
echo "DBUser=root" >> /etc/zabbix/zabbix_proxy.conf
echo "DBPassword="$password >> /etc/zabbix/zabbix_proxy.conf
echo "ProxyOfflineBuffer=48" >> /etc/zabbix/zabbix_proxy.conf
echo "StartPollers=5" >> /etc/zabbix/zabbix_proxy.conf
echo "StartPingers=1" >> /etc/zabbix/zabbix_proxy.conf
echo "StartDiscoverers=1" >> /etc/zabbix/zabbix_proxy.conf
echo "Timeout=4" >> /etc/zabbix/zabbix_proxy.conf
echo "ExternalScripts=/usr/lib/zabbix/externalscripts" >> /etc/zabbix/zabbix_proxy.conf
echo "FpingLocation=/usr/bin/fping" >> /etc/zabbix/zabbix_proxy.conf
echo "Fping6Location=/usr/bin/fping6" >> /etc/zabbix/zabbix_proxy.conf
echo "LogSlowQueries=3000" >> /etc/zabbix/zabbix_proxy.conf

# Restart Zabbix services
service zabbix-proxy restart
service zabbix-agent restart
